# Generated by Django 4.1.7 on 2023-10-30 14:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(max_length=3000)),
                ('price', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('reviews', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Product_Name', models.CharField(max_length=100000)),
                ('Product_Price', models.CharField(max_length=100)),
                ('Product_Reviews', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
